rest:
    resource: "@AppBundle/Resources/config/routing.yml"
    type:     rest
    prefix: /rest
user_rest:
    type: rest
    resource: AppBundle\Controller\UserController
    prefix: /authenticate